id: default
prompt: >-
  Look for new policies or policy changes in the last 1 Month. Report only NO POLICY, if there is no change. If there is
  a policy change or new policies then list them.
cron: 30 13 22 * *
mode: repeat
enabled: false
createdAt: '2026-08-22T07:57:08.392Z'
lastRunAt: '2026-08-22T08:00:02.775Z'
lastResult: success
