id: default
prompt: >-
  Check if any policies in gmail or drive have been changed in the last 7 days. Only give me a single YES or NO answer.
  Nothing else
cron: '*/15 * * * *'
mode: repeat
enabled: false
createdAt: '2026-08-21T13:13:20.445Z'
lastRunAt: '2026-08-21T13:15:17.483Z'
lastResult: success
