id: default
prompt: >-
  Read policies from gmail and drive, and give a single Yes or No answer, if any policy update has been there in the
  last 24 hours.
cron: '*/15 * * * *'
mode: repeat
enabled: true
createdAt: '2026-08-21T12:28:01.136Z'
lastRunAt: '2026-08-21T12:28:18.361Z'
lastResult: success
